apiVersion: apps/v1
kind: Deployment
metadata:
  name: sharestreet
  namespace: sharestreet
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: sharestreet
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: sharestreet
  namespace: sharestreet
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sharestreet
  targetCPUUtilizationPercentage: 80