apiVersion: v1
kind: Namespace
metadata:
  name: sharestreet
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sharestreet
  namespace: sharestreet
spec:
  selector:
    matchLabels:
      app: sharestreet
  replicas: 2
  template:
    metadata:
      labels:
        app: sharestreet
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: sharestreet
  namespace: sharestreet
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sharestreet
  targetCPUUtilizationPercentage: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sharestreet-lb
  namespace: sharestreet
spec:
  type: LoadBalancer
  selector:
    app: sharestreet
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80