apiVersion: v1
kind: Namespace
metadata:
  name: sharestreet
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sharestreet
  namespace: sharestreet
spec:
  selector:
    matchLabels:
      app: sharestreet
  replicas: 2
  template:
    metadata:
      labels:
        app: sharestreet
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 3
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: sharestreet
  namespace: sharestreet
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sharestreet
  targetCPUUtilizationPercentage: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sharestreet-svc
  namespace: sharestreet
spec:
  type: NodePort
  selector:
    app: sharestreet
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: sharestreet-ingress
  namespace: sharestreet
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "sharestreet-ingress"
    networking.gke.io/managed-certificates: sharestreet-cert
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: sharestreet-svc
          servicePort: 30080
---
apiVersion: networking.gke.io/v1beta2
kind: ManagedCertificate
metadata:
  name: sharestreet-cert
spec:
  domains:
    - www.sharestreet.space
    - sharestreet.space
